`python -m a003_pcap.b2_exceptions.c09_unhandled_exception`


_Menace_ is an _Exception_, but _Exception_ is not a _Menace_.